// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using System;
using TicTacToeWebsite.Data;

namespace TicTacToeWebsite.Migrations
{
    [DbContext(typeof(UserAccountDbContext))]
    partial class UserAccountDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("TicTacToeWebsite.Models.UserAccount", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConfirmPassword")
                        .IsRequired();

                    b.Property<long>("DoubleLoses");

                    b.Property<long>("DoubleTies");

                    b.Property<long>("DoubleWins");

                    b.Property<string>("EmailID")
                        .IsRequired();

                    b.Property<string>("FullName")
                        .IsRequired();

                    b.Property<string>("Password")
                        .IsRequired();

                    b.Property<long>("SingleEasyLoses");

                    b.Property<long>("SingleEasyTies");

                    b.Property<long>("SingleEasyWins");

                    b.Property<long>("SingleHardLoses");

                    b.Property<long>("SingleHardTies");

                    b.Property<long>("SingleHardWins");

                    b.Property<string>("UserName")
                        .IsRequired();

                    b.HasKey("ID");

                    b.ToTable("UserAccount");
                });
#pragma warning restore 612, 618
        }
    }
}
